### ISSUE TITLE
Does this support Windows?

### ISSUE THREAD

**Issue by AraHaan** [fafhrd91/setuptools-rust#1]
Does this support the latest rust on Windows as well? Also will this check for rust updates before compile to be sure the current build tool chain is installed/up to date?

**Comment by fafhrd91** [comment]
I didn't test on windows, but I don't see any reason why it should not work on windows.

**Comment by fafhrd91** [comment]
@AraHaan would you mind test it on windows?

**Comment by AraHaan** [comment]
Sure, if I had an test rust python module / pachage on pypi that would require building in rust.

**Comment by fafhrd91** [comment]
if you have windows with rust toolchain you can use example from this repo

**Comment by AraHaan** [comment]
ok
